version: '3.1'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: default
      POSTGRES_USER: prisma
      POSTGRES_PASSWORD: 123
    volumes:
      - ../data/postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  
  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: 123
    ports:
      - "5050:80"
    depends_on:
      - postgres